// INCLUSÃO DO CABEÇALHO DA BIBLIOTECA PADRÃO DO C. CABEÇALHO PADRÃO DE ENTRADA E SAÍDA DE DADOS
#include <stdio.h>
// INCLUSÃO DA BIBLIOTECA DE PROPÓSITO GERAL PADRÃO DA LINGUAGEM C. FUNÇÕES DE ALOCAÇÃO DE MEMÓRIA, CONTROLE DE PROCESSOS, CONVERSÕES E OUTRAS
#include <stdlib.h>

// MAIN() -> FUNÇÃO PRINCIPAL DE UM PROGRAMA EM C
// INT FUNÇÃO QUE NO FIM DEVOLVE UM NÚMERO INTEIRO
int main()
{
    // DECLARAÇÃO DA VARIÁVEL DE NOME PONTOS DO TIPO INTEIRO
    int pontos;

    // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite o número de seus pontos\n");

    // SCANF -> FUNÇÃO PARA LEITURA DE DADOS FORMATADOS VIA TECLADO
    scanf("%d", &pontos);

    // IF -> ESTRUTURA DE DECISÃO SIMPLES => SE A QUANTIDADE DE PONTOS INFORMADOS FOR MAIOR OU IGUAL A 1000 EXECUTA A FUNÇÃO DA LINHA 22
    if(pontos >= 1000);
    {
        // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
        printf("Voce passou de nivel!");
    }

}
