// INCLUSÃO DO CABEÇALHO DA BIBLIOTECA PADRÃO DO C. CABEÇALHO PADRÃO DE ENTRADA E SAÍDA DE DADOS
#include <stdio.h>
// INCLUSÃO DA BIBLIOTECA DE PROPÓSITO GERAL PADRÃO DA LINGUAGEM C. FUNÇÕES DE ALOCAÇÃO DE MEMÓRIA, CONTROLE DE PROCESSOS, CONVERSÕES E OUTRAS
#include <stdlib.h>

// MAIN() -> FUNÇÃO PRINCIPAL DE UM PROGRAMA EM C
// INT FUNÇÃO QUE NO FIM DEVOLVE UM NÚMERO INTEIRO
int main()
{
    // DECLARAÇÃO DA VARIÁVEL DE NOME NUMERO DO TIPO INTEIRO
    int a, b, c, soma ;

    // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite o valor de A\n");
    // SCANF -> FUNÇÃO PARA INSERÇÃO DE DADOS FORMATADOS VIA TECLADO
    scanf("%d", &a);

    // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite o valor de B\n");
    // SCANF -> FUNÇÃO PARA INSERÇÃO DE DADOS FORMATADOS VIA TECLADO
    scanf("%d", &b);

    // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite o valor de C\n");
    // SCANF -> FUNÇÃO PARA INSERÇÃO DE DADOS FORMATADOS VIA TECLADO
    scanf("%d", &c);

    // IF -> SE A SOMA DE A+B É MENOR DO QUE O VALOR DE C
    if(a+b<c){
        // ADIÇÃO -> VARIÁVEL SOMA É A ADIÇÃO DO VALOR DE A MAIS O VALOR DE B
        soma = a + b;
        // PRINTF -> EXIBA NA TELA O VALOR DA VARIÁVEL SOMA
        printf("A soma de A + B eh: %d", soma);
    }
}
