// INCLUSÃO DO CABEÇALHO DA BIBLIOTECA PADRÃO DO C. CABEÇALHO PADRÃO DE ENTRADA E SAÍDA DE DADOS
#include <stdio.h>
// INCLUSÃO DA BIBLIOTECA DE PROPÓSITO GERAL PADRÃO DA LINGUAGEM C. FUNÇÕES DE ALOCAÇÃO DE MEMÓRIA, CONTROLE DE PROCESSOS, CONVERSÕES E OUTRAS
#include <stdlib.h>

// MAIN() -> FUNÇÃO PRINCIPAL DE UM PROGRAMA EM C
// INT FUNÇÃO QUE NO FIM DEVOLVE UM NÚMERO INTEIRO
// VOID -> FUNÇÃO QUE NADA DEVOLVE, APENAS SE EXECUTA E CHEGA AO FIM SEM RETORNAR (RETURN) NADA

int main(void)
{
//DECLARAÇÃO DA VARIÁVEL NUMERO DO TIPO INTEIRO
int numero;

// SCANF -> FUNÇÃO PARA INSERÇÃO DE DADOS FORMATADOS VIA TECLADO
scanf("%d", &numero);

if (numero % 2 != 0);

printf("%d\nO número digitado é ímpar");

}
