// INCLUSÃO DO CABEÇALHO DA BIBLIOTECA PADRÃO DO C. CABEÇALHO PADRÃO DE ENTRADA E SAÍDA DE DADOS
#include <stdio.h>
// INCLUSÃO DA BIBLIOTECA DE PROPÓSITO GERAL PADRÃO DA LINGUAGEM C. FUNÇÕES DE ALOCAÇÃO DE MEMÓRIA, CONTROLE DE PROCESSOS, CONVERSÕES E OUTRAS
#include <stdlib.h>

// MAIN() -> FUNÇÃO PRINCIPAL DE UM PROGRAMA EM C
// INT FUNÇÃO QUE NO FIM DEVOLVE UM NÚMERO INTEIRO
// VOID -> FUNÇÃO QUE NADA DEVOLVE, APENAS SE EXECUTA E CHEGA AO FIM SEM RETORNAR (RETURN) NADA
int main (void)
{
    // DECLARAÇÃO DE VARIÁVEIS EM PONTO FLUTUANTE (NÚMEROS REAIS)
    float nota1, nota2, nota3, nota4, media;

    // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite a primeira nota do aluno: ");

    // SCANF -> FUNÇÃO PARA LEITURA DE DADOS FORMATADOS VIA TECLADO
    scanf("%f", &nota1);

     // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite a segunda nota do aluno: ");

    // SCANF -> FUNÇÃO PARA LEITURA DE DADOS FORMATADOS VIA TECLADO
    scanf("%f", &nota2);

     // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite a terceira nota do aluno: ");

    // SCANF -> FUNÇÃO PARA LEITURA DE DADOS FORMATADOS VIA TECLADO
    scanf("%f", &nota3);

     // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    printf("Digite a quarta nota do aluno: ");

    // SCANF -> FUNÇÃO PARA LEITURA DE DADOS FORMATADOS VIA TECLADO
    scanf("%f", &nota4);

    // OPERAÇÃO ARITMÉTICA QUE SOMA O VALOR DAS 4 NOTAS E DIVIDE POR 4 OBTENDO A NOTA MÉDIA DO ALUNO
    media = (nota1 + nota2 + nota3 + nota4) / 4;

    // PRINTF -> COMANDO USADO PARA EXIBIR NA TELA A MENSAGEM QUE ESTÁ ENTRE ASPAS
    // %.1f -> O NÚMERO QUE ESTIVER ENTRE O PONTO E O "f" SERÁ A PRECISÃO DE CASAS DECIMAIS
    printf(" Média do Aluno = %.2f\n", media);

    return 0;
}
